# Generated by Django 4.2.5 on 2023-09-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_Entrada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadiaTotal',
            fields=[
                ('idestadiatotal', models.AutoField(primary_key=True, serialize=False)),
                ('totalhoras', models.TimeField()),
                ('id_registro_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaz_Entrada.registrovehiculos')),
            ],
        ),
    ]
