# Generated by Django 4.2.5 on 2023-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_Entrada', '0002_estadiatotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueoDisponible',
            fields=[
                ('idParqueoDisponibel', models.AutoField(primary_key=True, serialize=False)),
                ('TotalParqueoDisponible', models.BigIntegerField()),
            ],
        ),
    ]
